#pragma config(Motor,  port1,           rightDrive,    tmotorVex393TurboSpeed_HBridge, openLoop, driveRight)
#pragma config(Motor,  port2,           liftL3,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           liftR3,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           liftL2,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           liftR2,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           liftL1,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           liftR1,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           intake,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          leftDrive,     tmotorVex393TurboSpeed_HBridge, openLoop, reversed, driveLeft)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void lift(int power){
 	motor[liftR1]=power;
  motor[liftR2]=power;
 	motor[liftR3]=power;
 	motor[liftL1]=power;
  motor[liftL2]=power;
  motor[liftL3]=power;
}
task main()
{
	while (true){
		motor[rightDrive]=vexRT[Ch2];
		motor[leftDrive]=vexRT[Ch3];
		if(vexRT(Btn6U)){
			lift(127);
		}
		if(vexRT[Btn6D]){
			lift(-127);
		}
		if(vexRT[Btn5U]){
			motor[intake]=127;
		}
		if(vexRT[Btn5D]){
			  motor[intake]=-127;
		}
	}
}
