#pragma config(Motor,  port2,           leftDrive,     tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           rightDrive,    tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           intake,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           liftR1,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           liftR2,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           liftR3,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           liftL1,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           liftL2,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          liftL3,        tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

void lift(int power){
	motor[liftL1]=power;
	motor[liftL2]=power;
	motor[liftL3]=power;
	motor[liftR1]=power;
	motor[liftR2]=power;
	motor[liftR3]=power;
}

void lift(){
	if(vexRT[Btn5U]){
		lift(128);
	}
	else if(vexRT[Btn5D]){
		lift(-128);
	}
	else{
		lift(0);
	}
}

void drive(){
	motor[rightDrive]=vexRT[Ch2];
	motor[leftDrive]=vexRT[Ch3];
}

void claw(){
	if(vexRT[Btn6U]){
		motor[intake]=128;
	}
	else if(vexRT[Btn6D]){
		motor[intake]=-128;
	}
	else{
		motor[intake]=10;
	}
}

void pre_auton() {}

task autonomous {
	lift(127);
	wait1Msec(200);
	lift(0);
	motor[leftDrive] = -127;
	motor[rightDrive] = -127;
	wait1Msec(1200);
	motor[leftDrive] = 0;
	motor[rightDrive] = 0;
	lift(127);
	wait1Msec(1000);
	lift(-127);
	wait1Msec(500);
}

task usercontrol(){
	while(true){
		drive();
		lift();
		//claw();
	}
}
