#pragma config(Sensor, dgtl12, liftBottom,     sensorTouch)
#pragma config(Motor,  port1,           liftRI,        tmotorVex393_HBridge, openLoop, reversed, driveLeft)
#pragma config(Motor,  port2,           liftLO,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           liftRO,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           liftLI,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           intake2,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           intake1,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           leftDrive1,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           leftDrive2,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           rightDrive1,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          rightDrive2,   tmotorVex393_HBridge, openLoop, reversed, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

void lift(int power){
	motor[liftLO]=power;
	motor[liftLI]=power;
	motor[liftRI]=power;
	motor[liftRO]=power;
}

void lift(){
	if(vexRT[Btn5U]){
		lift(127);
	}
	else if(SensorValue(liftBottom)==1){
		lift(0);
	}
	else if(vexRT[Btn5D]){
		lift(-127);
	}
	else{
			lift(10);
	}
}

void drive(){
	motor[rightDrive1]=vexRT[Ch2];
	motor[rightDrive2]=vexRT[Ch2];
	motor[leftDrive1]=vexRT[Ch3];
	motor[leftDrive2]=vexRT[Ch3];
}

void pre_auton() {}

bool applyPressure = false;
void intaker(){
	if(vexRT[Btn6U]){
		motor[intake1]=127;
		motor[intake2]=127;
		applyPressure = true;
	}
	else if(vexRT[Btn6D]){
		motor[intake1]=-90;
		motor[intake2]=-90;
		applyPressure = false;
	}
	else{
		motor[intake1]=applyPressure*20;
		motor[intake2]=applyPressure*20;
	}
}

void drive(int power){
	motor[rightDrive1]=power;
	motor[rightDrive2]=power;
	motor[leftDrive1]=power;
	motor[leftDrive2]=power;
}

task autonomous {

}

task usercontrol(){
	while(true){
		drive();
		lift();
		intaker();
		wait1Msec(10);
	}
}
