#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    clawPot2,       sensorPotentiometer)
#pragma config(Sensor, in2,    clawPot1,       sensorPotentiometer)
#pragma config(Sensor, dgtl1,  liftBottom,     sensorTouch)
#pragma config(Sensor, dgtl2,  autonRL,        sensorTouch)
#pragma config(Sensor, I2C_1,  driveR,         sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  driveL,         sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_3,  liftEncoder,    sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           liftL3,        tmotorVex393HighSpeed_HBridge, openLoop)
#pragma config(Motor,  port2,           leftDrive,     tmotorVex393HighSpeed_MC29, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port3,           rightDrive,    tmotorVex393HighSpeed_MC29, openLoop, reversed, encoderPort, I2C_2)
#pragma config(Motor,  port4,           intake2,       tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           intake1,       tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           liftL2,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port7,           liftL1,        tmotorVex393HighSpeed_MC29, openLoop, reversed, encoderPort, I2C_3)
#pragma config(Motor,  port8,           liftR2,        tmotorVex393HighSpeed_MC29, openLoop, driveRight)
#pragma config(Motor,  port9,           liftR1,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port10,          liftR3,        tmotorVex393HighSpeed_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"
float desiredLift = 0;

void lift(int val){
	motor[liftL1] = motor[liftL2] =motor[liftL3] = motor[liftR1] = motor[liftR2] = motor[liftR3] = val;
}

task driveControl(){
	while(true){
		motor[leftDrive] = abs(vexRT[Ch3])<10?0:vexRT[Ch3];
		motor[rightDrive] = abs(vexRT[Ch2])<10?0:vexRT[Ch2];
	}
}

int limit(int val, int min = -127, int max = 127){
	if(val>max){
		return max;
	}
	if(val<min){
		return min;
	}
	return val;
}

bool liftMoving = false;
void liftInputs () {
	if(vexRT[Btn5U]) {
			liftMoving = true;
			desiredLift -= 30;
			}else if (vexRT[Btn5D]) {
			liftMoving = true;
			if(SensorValue[liftBottom])
				desiredLift = SensorValue[liftEncoder];
			else
				desiredLift += 30;
			} else if(liftMoving) {
			liftMoving = false;
			desiredLift = SensorValue[liftEncoder];
		}
}

task liftControl(){
	float kP = 0.7;
	float kI = 0.01;
	float kD = 0.7;
	float error;
	float integral;
	float derivative;
	float lastError;
	float lastSensorValue;
	desiredLift = SensorValue[liftEncoder];

	while(true) {
		error = SensorValue[liftEncoder] - desiredLift;

		integral += error;
		if(error == 0 || error>200 || error<-200)
			integral = 0;
		else if(error>1000 || error<-1000)
			error = 1000;
		if(derivative==0 && integral==0)
			desiredLift = SensorValue[liftEncoder];
		if(integral>1500)
			integral = 1500;

		derivative = error - lastError;

		lastError = error;

		lastSensorValue = SensorValue[liftEncoder];

		lift((kP*error + kI*integral + kD*derivative));//*!SensorValue(liftBottom));

		delay(15);
	}
	/**while(true){
	if(vexRT[Btn5U]){
	lift(127);
	}
	else if(vexRT[Btn5D]){
	lift(-127);
	}
	else{
	lift(10);
	}
	}*/
}

bool movingIn = false;
bool moving = false;

typedef struct {
	float kP;
	float kI;
	float kD;
	float target;
	float error;
	float integral;
	float derivative;
	float lastError;
	float threshold;
} Claw;

Claw leftClaw;
Claw rightClaw;

void clawInit (float kP, float kI, float kD) {
	leftClaw.kP = kP;
	rightClaw.kP = kP;

	leftClaw.kI = kI;
	rightClaw.kI = kI;

	leftClaw.kD = kD;
	rightClaw.kD = kD;
}

void clawUpdate (Claw *claw, tSensors sensor, tMotor clawMotor) {
	claw->error = claw->target - SensorValue[sensor];

	claw->integral = claw->integral + claw->error;

	if(claw->error == 0)
		claw->integral = 0;
	if(abs(claw->error)<25)
		claw->integral = 0;

	claw->derivative = claw->error - claw->lastError;

	claw->lastError = claw->error;

	motor[clawMotor] = limit(claw->kP*claw->error + claw->kI*claw->integral + claw->kD*claw->derivative , moving?-127:-30 ,moving?127:30);
}



void clawSetDegrees (int deg) {
	leftClaw.target = -0.0352*pow(deg,2) + 23.536*deg + 194.32;
	rightClaw.target = -0.0302*pow(deg,2) + 21.176*deg + 268.19;
}

float clawValuesToDegrees () {
	return 334.318-0.227273*sqrt(2270720-550*leftClaw.target);
}

float degree;
void clawInputs () {
	if(vexRT[Btn6U]) {
			degree = degree>240?240:degree+2.25;
			moving = true;
			movingIn = true;
			} else if(vexRT[Btn6D]) {
			degree-=2.25;
			moving = true;
			movingIn = false;
			} else if(movingIn) {
			degree = clawValuesToDegrees();
			degree = degree>240?240:degree;
			movingIn = false;
			moving = false;
			} else if(moving) {
			degree = clawValuesToDegrees();
			leftClaw.integral = 0;
			rightClaw.integral = 0;
			moving = false;
		}
		clawSetDegrees(degree);
	}

task clawControl () {
	clawInit(0.1, 0.0003, 0.3);

	degree = 90;

	leftClaw.target = SensorValue[clawPot1];
	rightClaw.target = SensorValue[clawPot2];

	while(true) {
		clawUpdate(leftClaw, clawPot1, intake1);
		clawUpdate(rightClaw, clawPot2, intake2);

		delay(10);
	}
}

//bool clawMovingOut1 = false;
//bool clawInMotion1 = false;
//task clawControl1(){
//  float Kp = 0.15;
//	float Ki = 0.008;
//	float Kd = 1.2;
//  float error;
//  float integral;
//  float derivative;
//  float previous_error;
//	desiredClaw1 = SensorValue[clawPot1];

//  while(true) {
//    if(vexRT[Btn6U]) {
//			if(clawMovingOut1)
//				desiredClaw1 = SensorValue[clawPot1];
//			desiredClaw1 -= 70;
//			clawMovingOut1 = false;
//			clawInMotion1 = true;
//		} else if (vexRT[Btn6D]) {
//			if(!clawMovingOut1)
//				desiredClaw1 = SensorValue[clawPot1];
//			desiredClaw1 += 70;
//			clawMovingOut1 = true;
//			clawInMotion1 = true;
//		} else if (clawInMotion1) {
//			clawInMotion1 = false;
//			desiredClaw1 = SensorValue[clawPot1]-((!clawMovingOut1)*70);
//		}

//    error = (desiredClaw1) - (SensorValue[clawPot1]);
//    integral = integral + error;
//    if (error == 0) {
//      integral = 0;
//    }
//    if ( abs(error) > 40) {
//      integral = 0;
//    }
//    derivative = error - previous_error;
//    previous_error = error;
//    motor[intake1] = Kp*error + Ki*integral + Kd*derivative;
//  }
//}

//bool clawMovingOut2 = false;
//bool clawInMotion2 = false;
//task clawControl2(){
//  float Kp = 0.15;
//	float Ki = 0.008;
//	float Kd = 1.2;
//  float error;
//  float integral;
//  float derivative;
//  float previous_error;
//	desiredClaw2 = SensorValue[clawPot2];

//  while(true) {
//    if(vexRT[Btn6U]) {
//			if(clawMovingOut2)
//				desiredClaw2 = SensorValue[clawPot2];
//			desiredClaw2 -= 70;
//			clawMovingOut2 = false;
//			clawInMotion2 = true;
//		} else if (vexRT[Btn6D]) {
//			if(!clawMovingOut2)
//				desiredClaw2 = SensorValue[clawPot2];
//			desiredClaw2 += 70;
//			clawMovingOut2 = true;
//			clawInMotion2 = true;
//		} else if (clawInMotion2) {
//			clawInMotion2 = false;
//			desiredClaw2 = SensorValue[clawPot2]-((!clawMovingOut2)*70);
//		}

//    error = (desiredClaw2) - (SensorValue[clawPot2]);
//    integral = integral + error;
//    if (error == 0) {
//      integral = 0;
//    }
//    if ( abs(error) > 40) {
//      integral = 0;
//    }
//    derivative = error - previous_error;
//    previous_error = error;
//    motor[intake2] = Kp*error + Ki*integral + Kd*derivative;
//  }
//}

void resetEncoders() {
	nMotorEncoder[rightDrive]=0;
	nMotorEncoder[leftDrive]=0;
	nMotorEncoder[liftEncoder]=0;
}

void drive(int power){
	motor[leftDrive]=motor[rightDrive]=power;
}

task autonR(){
	resetEncoders();
	desiredLift=0;
	startTask(liftControl);
	desiredLift=-844;
	wait1Msec(100);
	startTask(clawControl);
	leftClaw.target=2919.71;
	rightClaw.target=2752;
	wait1Msec(50);
	desiredLift=0;
	wait1Msec(100);
	while(nMotorEncoder(rightDrive)>-1400){
		drive(127);
		delay(3);
	}
	drive(0);
	leftClaw.target=3850;
	rightClaw.target=3645;
	wait1Msec(100);
	desiredLift=-700;
	wait1Msec(75);
	while(nMotorEncoder(rightDrive)>-345){
		motor[leftDrive]=-45;
		motor[rightDrive]=127;
		delay(3);
	}
	drive(0);
	while(nMotorEncoder(rightDrive)>-1420){
		drive(127);
		delay(3);
	}
	drive(0);
	desiredLift=-1250;
	wait1Msec(250);
	leftClaw.target=2919;
	rightClaw.target=2752;
	wait1Msec(75);
	desiredLift=0;
	while(nMotorEncoder(rightDrive)>-1500){
		motor[rightDrive]=29;
		motor[leftDrive]=128;
		delay(3);
	}
	drive(0);
	leftClaw.target=2919.71;
	rightClaw.target=2752;
	wait1Msec(75);
	desiredLift=-500;
	wait1Msec(100);
	while(nMotorEncoder(rightDrive)>-3450){
		motor[rightDrive]=127;
		motor[leftDrive]=56;
		delay(3);
	}
	drive(0);
	desiredLift=-1247;
	leftClaw.target=2919.71;
	rightClaw.target=2752;
	wait1Msec(125);
	desiredLift=0;
	//END TASKS
}

void autonL(){
	//add this by changing sides
	wait1Msec(100);
}

void pre_auton() {
	resetEncoders();
}

task autonomous {
	resetEncoders();
	while(nMotorEncoder(liftEncoder)>50){
		lift(127);
		delay(3);
	}
	while(nMotorEncoder(liftEncoder)<-50){
		lift(-127);
		delay(3);
	}
	lift(0);
	while(nMotorEncoder(liftEncoder)>-844){
		lift(127);
		delay(3);
	}
	lift(0);
	startTask(clawControl);
	leftClaw.target=2919.71;
	rightClaw.target=2752;
	wait1Msec(750);
	while(nMotorEncoder(liftEncoder)<-50){
		lift(-127);
		delay(3);
	}
	lift(0);
	while(nMotorEncoder(rightDrive)>-1400){
		drive(127);
		delay(3);
	}
	drive(0);
	leftClaw.target=3700;
	rightClaw.target=3495;
	wait1Msec(750);
	while(nMotorEncoder(liftEncoder)>-700){
		lift(127);
		delay(3);
	}
	lift(0);
	while(nMotorEncoder(rightDrive)<200){
		drive(-127);
		delay(3);
	}
	while(nMotorEncoder(rightDrive)>-345){
		motor[leftDrive]=-45;
		motor[rightDrive]=-127;
		delay(3);
	}
	drive(0);
	while(nMotorEncoder(rightDrive)>-1420){
		drive(-127);
		delay(3);
	}
	drive(0);
	while(nMotorEncoder(liftEncoder)>-1250){
		lift(127);
		delay(3);
	}
	lift(0);
	leftClaw.target=2919;
	rightClaw.target=2752;
	wait1Msec(750);
	while(nMotorEncoder(liftEncoder)<-50){
		lift(-127);
		delay(3);
	}
	lift(0);
	while(nMotorEncoder(rightDrive)>-1500){
		motor[rightDrive]=29;
		motor[leftDrive]=128;
		delay(3);
	}
	drive(0);
	leftClaw.target=2919.71;
	rightClaw.target=2752;
	wait1Msec(750);
	while(nMotorEncoder(liftEncoder)>-844){
		lift(127);
		delay(3);
	}
	lift(0);
	while(nMotorEncoder(rightDrive)>-3450){
		motor[rightDrive]=127;
		motor[leftDrive]=56;
		delay(3);
	}
	drive(0);
	while(nMotorEncoder(liftEncoder)>-1247){
		lift(127);
		delay(3);
	}
	lift(0);
	leftClaw.target=2919.71;
	rightClaw.target=2752;
	wait1Msec(750);
	while(nMotorEncoder(liftEncoder)<-50){
		lift(-127);
		delay(3);
	}
	lift(0);
	stopAllTasks();
}

task usercontrol(){
	resetEncoders();
	startTask(clawControl);
	startTask(liftControl);
	startTask(driveControl);
	while(true) {
		liftInputs();
		clawInputs();
		delay(10);
	}
}
