#pragma config(Sensor, dgtl1,  liftBottom,     sensorTouch)
#pragma config(Motor,  port1,           liftL3,        tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           liftR1,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           liftR2,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           leftDrive,     tmotorVex393HighSpeed_MC29, openLoop, driveLeft)
#pragma config(Motor,  port5,           liftL1,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           liftL2,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           rightDrive,    tmotorVex393HighSpeed_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port8,            ,             tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           intake,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          liftR3,        tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

void lift(int power){
	motor[liftL1]=power;
	motor[liftL2]=power;
	motor[liftL3]=power;
	motor[liftR1]=power;
	motor[liftR2]=power;
	motor[liftR3]=power;
}

void lift(){
	if(vexRT[Btn5U]){
		lift(127);
	}
	else if(SensorValue(liftBottom)==1){
		lift(0);
	}
	else if(vexRT[Btn5D]){
		lift(-127);
	}
	else{
			lift(7);
	}
}

void drive(){
	motor[rightDrive]=abs(vexRT[Ch2])<10?0:vexRT[Ch2];
	motor[leftDrive]=abs(vexRT[Ch3])<10?0:vexRT[Ch3];
}

void pre_auton() {}

void intaker(){
	if(vexRT[Btn6U]){
		motor[intake]=127;
	}
	else if(vexRT[Btn6D]){
		motor[intake]=-127;
	}
	else{
		motor[intake]=5;
	}
}

task autonomous {
	lift(127);
	wait1Msec(200);
	lift(0);
	motor[leftDrive] = 127;
	motor[rightDrive] = 127;
	wait1Msec(300);
	motor[intake]=127;
	wait1Msec(200)
	motor[intake]=0;
	wait1Msec(300);
	motor[leftDrive] = 0;
	motor[rightDrive] = 0;
	lift(127);
	wait1Msec(150);
	motor[leftDrive] = 127;
	motor[rightDrive] = 127;
	wait1Msec(500);
	lift(0);
	wait1Msec(200);
	motor[leftDrive] = 0;
	motor[rightDrive] = 0;
}

task usercontrol(){
	while(true){
		drive();
		lift();
		//claw();
		intaker();
		wait1Msec(25);
	}
}
