#pragma config(Sensor, dgtl1,  liftBottom,     sensorTouch)
#pragma config(Motor,  port1,           liftL3,        tmotorVex393HighSpeed_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           leftDrive,     tmotorVex393HighSpeed_MC29, openLoop, encoderPort, None)
#pragma config(Motor,  port3,           rightDrive,    tmotorVex393HighSpeed_MC29, openLoop, reversed, encoderPort, None)
#pragma config(Motor,  port4,           intake,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           liftL2,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port7,           liftL1,        tmotorVex393HighSpeed_MC29, openLoop, reversed, encoderPort, None)
#pragma config(Motor,  port8,           liftR2,        tmotorVex393HighSpeed_MC29, openLoop, driveRight, encoderPort, None)
#pragma config(Motor,  port9,           liftR1,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port10,          liftR3,        tmotorVex393HighSpeed_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

void lift(int power){
	motor[liftL1]=power;
	motor[liftL2]=power;
	motor[liftR1]=power;
	motor[liftR2]=power;
}

void lift(){
	if(vexRT[Btn5U]){
		lift(127);
	}
	else if(SensorValue(liftBottom)==1){
		lift(0);
	}
	else if(vexRT[Btn5D]){
		lift(-127);
	}
	else{
			lift(10);
	}
}

void drive(){
	motor[rightDrive]=vexRT[Ch2];
	motor[leftDrive]=vexRT[Ch3];
}

void pre_auton() {}

bool applyPressure = false;
bool stopClose=false;
void intaker(){
	if(vexRT[Btn6U]){
		motor[intake]=127;
		applyPressure = true;
		stopClose=true;
	}
	else if (vexRT[Btn8U]&&stopClose){
		applyPressure=false;
		motor[intake]=0;
		stopClose=false;
		wait1Msec(50);
	}
	else if(vexRT[Btn8D]){
		motor[intake]=-90;
		applyPressure = false;
	}
	else{
		motor[intake]=applyPressure*20;
	}
}

void drive(int power){
	motor[rightDrive]=power;
	motor[leftDrive]=power;
}

task autonomous {
	lift(127);
	wait1Msec(200);
	lift(0);
	drive(127);
	wait1Msec(200);
	motor[intake]=127;
	wait1Msec(350);
	motor[intake]=0;
	wait1Msec(225);
	drive(0);
	lift(127);
	wait1Msec(500);
	drive(127);
	wait1Msec(325);
	lift(0);
	wait1Msec(360);
	drive(0);

	/***/
}

task usercontrol(){
	while(true){
		drive();
		lift();
		intaker();
		wait1Msec(10);
	}
}
