#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    clawPot,        sensorPotentiometer)
#pragma config(Sensor, dgtl1,  liftBottom,     sensorTouch)
#pragma config(Sensor, dgtl2,  autonRL,        sensorTouch)
#pragma config(Sensor, I2C_1,  driveR,         sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  driveL,         sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_3,  liftEncoder,    sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           liftL3,        tmotorVex393HighSpeed_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           leftDrive,     tmotorVex393HighSpeed_MC29, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port3,           rightDrive,    tmotorVex393HighSpeed_MC29, openLoop, reversed, encoderPort, I2C_2)
#pragma config(Motor,  port4,           intake2,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           intake1,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           liftL2,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port7,           liftL1,        tmotorVex393HighSpeed_MC29, openLoop, reversed, encoderPort, I2C_3)
#pragma config(Motor,  port8,           liftR2,        tmotorVex393HighSpeed_MC29, openLoop, driveRight, encoderPort, I2C_2)
#pragma config(Motor,  port9,           liftR1,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port10,          liftR3,        tmotorVex393HighSpeed_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"
float desiredClaw = 0;
float desiredLift = 0;

void lift(int val){
	motor[liftL1] = motor[liftL2] =motor[liftL3] = motor[liftR1] = motor[liftR2] = motor[liftR3] = val;
}

task driveControl(){
	while(true){
    motor[leftDrive] = abs(vexRT[Ch3])<10?0:vexRT[Ch3];
  	motor[rightDrive] = abs(vexRT[Ch2])<10?0:vexRT[Ch2];
	}
}

int limit(int val, int min = -127, int max = 127){
	if(val>max){
		return max;
	}
	if(val<min){
		return min;
	}
	return val;
}

task liftControl(){
  float kP = 0.2;
	float kI = 0.01;
	float kD = 0.7;
  float error;
  float integral;
  float derivative;
	desiredLift = SensorValue[liftEncoder];

  while(true) {
    if(vexRT[Btn5U]) {
			desiredLift += 20;
		} else if (vexRT[Btn5D]) {
			desiredLift -= 20;
		}


    error = SensorValue[liftEncoder] - desiredLift;

		integral += error;
		if(error == 0 || abs(error)>200)
			integral = 0;
		else if(abs(error)>1000)
			error = 1000;
		if(derivative==0 && integral==0)
			desiredLift = SensorValue[liftEncoder];
		if(integral>1500)
			integral = 1500;

		derivative = error - lastError;

		lastError = error;

		lastSensorValue = SensorValue[liftEncoder];

		lift(kP*error + kI*integral + kD*derivative);

		delay(5);
}

bool clawMovingOut = false;
bool clawInMotion = false;
task clawControl(){
  float kP = 0.2;
	float kI = 0.01;
	float kD = 0.7;
  float error;
  float integral;
  float derivative;
	desiredClaw = SensorValue[clawPot];

  while(true) {
    if(vexRT[Btn6U]) {
			if(clawMovingOut)
				desiredClaw = SensorValue[clawPot];
			desiredClaw -= 70;
			clawMovingOut = false;
			clawInMotion = true;
		} else if (vexRT[Btn6D]) {
			if(!clawMovingOut)
				desiredClaw = SensorValue[clawPot];
			desiredClaw += 70;
			clawMovingOut = true;
			clawInMotion = true;
		} else if (clawInMotion) {
			clawInMotion = false;
			desiredClaw = SensorValue[clawPot]-((!clawMovingOut)*70);
		}


    error = SensorValue[clawPot] - desiredClaw;

		integral += error;
		if(error == 0 || abs(error)>200)
			integral = 0;
		else if(abs(error)>1000)
			error = 1000;
		if(derivative==0 && integral==0)
			desiredClaw = SensorValue[clawPot];
		if(integral>1500)
			integral = 1500;

		derivative = error - lastError;

		lastError = error;

		lastSensorValue = SensorValue[clawPot];

		motor[intake1] = motor[intake2] = kP*error + kI*integral + kD*derivative;

		delay(5);
	}
}


void resetEncoders(){
	nMotorEncoder[rightDrive]=0;
	nMotorEncoder[leftDrive]=0;
	nMotorEncoder[liftEncoder]=0;
}

void drive(int power){
	motor[leftDrive]=motor[rightDrive]=power;
}

void autonR(){
	resetEncoders();
	startTask(clawControl);
	startTask(liftControl);
	desiredClaw=1900;
	desiredLift=50;
	while(nMotorEncoder(rightDrive)<150){
		drive(127);
		delay(3);
	}
	drive(0);
	desiredClaw=1000;
	desiredLift=0;
	while(nMotorEncoder(rightDrive)<180){
		drive(127);
		delay(3);
	}
	drive(0);
	desiredClaw=1900;
	desiredLift=75;
	while(nMotorEncoder(rightDrive)<225){
		drive(127);
		delay(3);
	}
	drive(0);
	while(nMotorEncoder(leftDrive)>160){
		motor[leftDrive]=-127;
		delay(3);
	}
	while(nMotorEncoder(rightDrive)<275){
		drive(127);
		delay(3);
	}
	drive(0);
	motor[leftDrive]=0;
	desiredLift=500;
	wait1Msec(250);
	desiredClaw=500;
	wait1Msec(75);
	desiredLift=0;
	desiredClaw=1000;
	while(nMotorEncoder(rightDrive)<325){
		motor[rightDrive]=127;
		delay(3);
	}
	motor[rightDrive]=0;
	while(nMotorEncoder(rightDrive)<450){
		drive(127);
		delay(3);
	}
	while(nMotorEncoder(leftDrive)<325){
		motor[leftDrive]=127;
		delay(3);
	}
	motor[leftDrive]=0;
	while(nMotorEncoder(rightDrive)<550){
		drive(127);
		delay(3);
	}
	drive(0);
	desiredClaw=1900;
	wait1Msec(150);
	desiredLift=50;
	wait1Msec(100);
	while(nMotorEncoder(leftDrive)<450){
		motor[leftDrive]=127;
		delay(3);
	}
	motor[leftDrive]=0;
	while(nMotorEncoder(rightDrive)<700){
		drive(127);
		delay(3);
	}
	drive(0);
	desiredLift=500;
	wait1Msec(250);
	desiredClaw=500;
	wait1Msec(75);
	desiredLift=0;
	desiredClaw=1000;
}

void autonL(){
	wait1Msec(100);
}

void pre_auton() {
	resetEncoders();
}

task autonomous {
	/**
	lift(127);
	wait1Msec(200);
	lift(0);
	drive(-127);
	wait1Msec(100);
	drive(0);
	motor[intake1]=127;
	motor[intake2]=127;
	wait1Msec(500);
	motor[intake1]=0;
	motor[intake2]=0;
	lift(127);
	wait1Msec(50);
	lift(0);
	drive(-127);
	wait1Msec(1100);
	drive(10);
	lift(127);
	wait1Msec(700);
	motor[intake1]=127;
	motor[intake2]=127;
	wait1Msec(300);
	drive(0);
	motor[intake1]=0;
	motor[intake2]=0;
	*/
	autonR();
}

task usercontrol(){
	startTask(clawControl);
	startTask(liftControl);
	startTask(driveControl);
}
