#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    intakeClaw,     sensorPotentiometer)
#pragma config(Sensor, dgtl1,  liftBottom,     sensorTouch)
#pragma config(Sensor, dgtl2,  autonRL,        sensorTouch)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_3,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           liftR3,        tmotorVex393HighSpeed_HBridge, openLoop)
#pragma config(Motor,  port2,           liftR1,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           liftR2,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           leftDrive,     tmotorVex393HighSpeed_MC29, openLoop, driveLeft, encoderPort, I2C_1)
#pragma config(Motor,  port5,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           liftL2,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port7,           liftL1,        tmotorVex393HighSpeed_MC29, openLoop, reversed, encoderPort, I2C_3)
#pragma config(Motor,  port8,           rightDrive,    tmotorVex393HighSpeed_MC29, openLoop, reversed, driveRight, encoderPort, I2C_2)
#pragma config(Motor,  port9,           intake,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port10,          liftL3,        tmotorVex393HighSpeed_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

void lift(int power){
	motor[liftL1]=motor[liftL2]=motor[liftL3]=motor[liftR1]=motor[liftR2]=motor[liftR3]=power;
}

void lift(){
	if(vexRT[Btn5U]){
		lift(127);
	}
	else if(vexRT[Btn5D]){
		lift(-127);
	}
	else{
		lift(10);
	}
}

void drive(){
	motor[rightDrive]=vexRT[Ch2];
	motor[leftDrive]=vexRT[Ch3];
}

bool applyPressure = false;
void claw(){
	if(vexRT[Btn6U]){
		motor[intake]=127;
		applyPressure=true;
	}
	else if(vexRT[Btn6D]){
		motor[intake]=-100;
		applyPressure = false;
	}
	else{
		motor[intake]=applyPressure*10;
	}
}

void pre_auton() {}

task autonomous {
	lift(127);
	wait1Msec(200);
	lift(0);
	motor[leftDrive] = -127;
	motor[rightDrive] = -127;
	wait1Msec(1200);
	motor[leftDrive] = 0;
	motor[rightDrive] = 0;
	lift(127);
	wait1Msec(1000);
	lift(-127);
	wait1Msec(500);
}

task usercontrol(){
	while(true){
		drive();
		lift();
		claw();
	}
}
