#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    clawPot,        sensorPotentiometer)
#pragma config(Sensor, dgtl1,  liftBottom,     sensorTouch)
#pragma config(Sensor, dgtl2,  autonRL,        sensorTouch)
#pragma config(Sensor, I2C_1,  driveR,         sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  driveL,         sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_3,  liftEncoder,    sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           liftL3,        tmotorVex393HighSpeed_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           leftDrive,     tmotorVex393HighSpeed_MC29, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port3,           rightDrive,    tmotorVex393HighSpeed_MC29, openLoop, reversed, encoderPort, I2C_2)
#pragma config(Motor,  port4,           intake2,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           intake1,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           liftL2,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port7,           liftL1,        tmotorVex393HighSpeed_MC29, openLoop, reversed, encoderPort, I2C_3)
#pragma config(Motor,  port8,           liftR2,        tmotorVex393HighSpeed_MC29, openLoop, driveRight, encoderPort, I2C_2)
#pragma config(Motor,  port9,           liftR1,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port10,          liftR3,        tmotorVex393HighSpeed_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"
float desiredClaw = 0;
float desiredLift = 0;

void setLift(int val){
	motor[liftL1] = motor[liftL2] =motor[liftL3] = motor[liftR1] = motor[liftR2] = motor[liftR3] = val;
}

void drive(){
	motor[rightDrive]=vexRT[Ch2];
	motor[leftDrive]=vexRT[Ch3];
}

int limit(int val, int min = -127, int max = 127){
	if(val>max){
		return max;
	}
	if(val<min){
		return min;
	}
	return val;
}

task liftControl(){
int old;
while(true){
	if(vexRT[Btn5U]){
		desiredLift+=10;
		old = SensorValue(liftEncoder);
	}
	else if(vexRT[Btn5D]){
		desiredLift-=10;
		old = SensorValue(liftEncoder);
		if(desiredLift<500){
			desiredLift = -49;
			old = desiredLift;
		}
	}
	else{
		desiredLift = old;
	}
	desiredLift = limit(desiredLift,-50,1250);
	setLift((desiredLift - SensorValue(liftEncoder))*0.5);
	delay(3);
	}
}


task clawControl(){
	int old;
	while(true){
		if(vexRT[Btn6U]){
			desiredClaw-=15;
			old = SensorValue(clawPot);
		}
		else if(vexRT[Btn6D]){
			desiredClaw+=15;
			old = SensorValue(clawPot);
		}
		else{
			desiredClaw = old-((desiredClaw<300)?5500:0);
		}
		desiredClaw = limit(desiredClaw,150,1300);
		motor[intake1] = -((desiredClaw - SensorValue(clawPot))*0.2);
		motor[intake2] = -((desiredClaw - SensorValue(clawPot))*0.2);
		delay(1);
	}
}


void resetEncoders(){
	nMotorEncoder[rightDrive]=0;
	nMotorEncoder[leftDrive]=0;
	nMotorEncoder[liftL1]=0;
}

void autonR(){
	resetEncoders();
	motor[intake]=127;
	wait1Msec(625);
	lift(127);
	wait1Msec(150);
	lift(0);
	motor[intake]=0;
	while(nMotorEncoder(rightDrive2)<25){
		rightDrive(127);
		delay(5);
	}
	while(nMotorEncoder(leftDrive2)<150){
		drive(127);
		delay(5);
	}
	lift(-127);
	wait1Msec(125);
	motor[intake]=-127;
	wait1Msec(200);
	while(nMotorEncoder(leftDrive2)>125){
		drive(-127);
		delay(5);
	}
	motor[intake]=127;
	wait1Msec(215);
	motor[intake]=50;
	lift(127);
	wait1Msec(350);
	lift(10);
	motor[intake]=15;
	while(nMotorEncoder(leftDrive2)<-50){
		leftDrive(-127);
		delay(5);
	}
	while(nMotorEncoder(rightDrive2)>-125){
		drive(-127);
		delay(5);
	}
	drive(0);
	lift(128);
	wait1Msec(400);
	motor[intake]=-128;
	wait1Msec(50);
	lift(0);
	wait1Msec(125);
	motor[intake]=0;
}

void autonL(){
	resetEncoders();
	motor[intake]=127;
	wait1Msec(625);
	lift(127);
	wait1Msec(150);
	lift(0);
	motor[intake]=0;
	while(nMotorEncoder(rightDrive2)<25){
		rightDrive(127);
		delay(5);
	}
	while(nMotorEncoder(leftDrive2)<150){
		drive(127);
		delay(5);
	}
	lift(-127);
	wait1Msec(125);
	motor[intake]=-127;
	wait1Msec(200);
	while(nMotorEncoder(leftDrive2)>125){
		drive(-127);
		delay(5);
	}
	motor[intake]=127;
	wait1Msec(215);
	motor[intake]=50;
	lift(127);
	wait1Msec(350);
	lift(10);
	motor[intake]=15;
	while(nMotorEncoder(leftDrive2)<-50){
		leftDrive(-127);
		delay(5);
	}
	while(nMotorEncoder(rightDrive2)>-125){
		drive(-127);
		delay(5);
	}
	drive(0);
	lift(128);
	wait1Msec(400);
	motor[intake]=-128;
	wait1Msec(50);
	lift(0);
	wait1Msec(125);
	motor[intake]=0;
}

void pre_auton() {
	resetEncoders();
}

task autonomous {
	/**lift(127);
	wait1Msec(200);
	lift(0);
	motor[leftDrive] = -127;
	motor[rightDrive] = -127;
	wait1Msec(1200);
	motor[leftDrive] = 0;
	motor[rightDrive] = 0;
	lift(127);
	wait1Msec(1000);
	lift(-127);
	wait1Msec(500);*/
	if(autonRL==true){
		autonL();
	}
	else{
		autonR();
	}
}

task usercontrol(){
	startTask(clawControl);
	startTask(liftControl);
	while(true){
		drive();
		delay(5);
	}
}
